"""Public API for AOTD, FOTD, dynamics, and nonlinear comparison solvers."""

from . import burgers_setting
from .burgers_setting import N_X, N_U, set_dims
from .burgers import (
    BurgersParams,
    burgers_grid,
    burgers_x0,
    burgers_target,
    peclet,
    make_step_fns,
)
from .swing import (
    SwingParams,
    make_swing_step_fns,
    make_swing_problem,
    swing_x0,
    make_schedule,
    N_BUS,
    INERTIA_SCALES,
)
from .ComputeKKT import (
    Problem,
    n_z,
    n_lam,
    n_kkt,
    x_indices,
    u_indices,
    lam_indices,
    z_size,
    lam_size,
    cost,
    lagrangian,
    grad_cost,
    grad_lagrangian,
    hessian_blocks,
    modify_hessian_blocks,
    constraint_residual,
    constraint_jacobian,
    stage_jacobians,
    rollout,
    assemble_kkt,
)
from .CalculateAug import merit, grad_merit, grad_merit_flat
from .backtrack import armijo
from .composition import (
    uniform_knots,
    subproblem_range,
    core_range,
    compose,
    decompose_residual_norms,
)
from .AOTDNLP import (
    Subproblem,
    build_subproblems,
    assemble,
    n_local,
    n_z_local,
    n_lam_local,
    local_residual,
)
from .AOTDsolver import (
    solve,
    SOLVER_DISPATCH,
    gmres_qlp_core,
    qlp_min_length,
    schur_approx_preconditioner,
    ilu_schur_preconditioner,
    spectral_norm_2,
)
from .AOTD import AlgorithmConfig, run_algorithm, eps_max_value

from .baselines.common import BaselineResult, kkt_residual
from .baselines.LongNLP import solve_ipopt
from .baselines.MulShoot import solve_multishoot
from .baselines.Schwarz import solve_schwarz
from .baselines.ADMM import solve_admm

__all__ = [
    "burgers_setting",
    "N_X",
    "N_U",
    "set_dims",
    "BurgersParams",
    "burgers_grid",
    "burgers_x0",
    "burgers_target",
    "peclet",
    "make_step_fns",
    "SwingParams",
    "make_swing_step_fns",
    "make_swing_problem",
    "swing_x0",
    "make_schedule",
    "N_BUS",
    "INERTIA_SCALES",
    "Problem",
    "n_z",
    "n_lam",
    "n_kkt",
    "x_indices",
    "u_indices",
    "lam_indices",
    "z_size",
    "lam_size",
    "cost",
    "lagrangian",
    "grad_cost",
    "grad_lagrangian",
    "hessian_blocks",
    "modify_hessian_blocks",
    "constraint_residual",
    "constraint_jacobian",
    "stage_jacobians",
    "rollout",
    "assemble_kkt",
    "merit",
    "grad_merit",
    "grad_merit_flat",
    "armijo",
    "uniform_knots",
    "subproblem_range",
    "core_range",
    "compose",
    "decompose_residual_norms",
    "Subproblem",
    "build_subproblems",
    "assemble",
    "n_local",
    "n_z_local",
    "n_lam_local",
    "local_residual",
    "solve",
    "SOLVER_DISPATCH",
    "gmres_qlp_core",
    "qlp_min_length",
    "schur_approx_preconditioner",
    "ilu_schur_preconditioner",
    "spectral_norm_2",
    "AlgorithmConfig",
    "run_algorithm",
    "eps_max_value",
    "BaselineResult",
    "kkt_residual",
    "solve_ipopt",
    "solve_multishoot",
    "solve_schwarz",
    "solve_admm",
]
